export const EventCategory = {
  CONFERENCE: 'CONFERENCE',
  WORKSHOP: 'WORKSHOP',
  CONCERT: 'CONCERT',
  SPORTS: 'SPORTS',
  SOCIAL: 'SOCIAL',
  EDUCATIONAL: 'EDUCATIONAL',
  ENTERTAINMENT: 'ENTERTAINMENT',
  BUSINESS: 'BUSINESS',
  CHARITY: 'CHARITY',
  OTHER: 'OTHER'
};

export const PrivacySettings = {
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE',
  INVITE_ONLY: 'INVITE_ONLY'
};
